---
version: 2
multicolumn: false
web-width: 650px
align: center
float: h!
grid:
  rows: 1
  columns: 1
  grid_elements:
  - path: figures/Fig15/Fig15.png
    type: static
    from:
    - 1
    - 1
    to:
    - 1
    - 1
    url: "/users/336192/articles/462559/master/file/figures/Fig15/Fig15.png"
    folder_url: "/users/336192/articles/462559/master/folder/figures/Fig15"
